/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button_fanOn:285534:
  println("Fans: ON");
  myPort.write("FN");
} //_CODE_:button_fanOn:285534:

public void button1_click2(GButton source, GEvent event) { //_CODE_:button_fansOff:818199:
  println("Fans: OFF");
  myPort.write("FF");
} //_CODE_:button_fansOff:818199:

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:809526:
  println("CCW - GCheckbox >> GEvent." + event + " @ " + millis());
  println(event);
  if (checkbox1.isSelected()) {
    println("turn CW");
    myPort.write("CW");
  } else {
    println("turn CCW");
    myPort.write("CCW");
  }
} //_CODE_:checkbox1:809526:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:357951:
  //  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
  //  println(textfield1.getText());
  //  String send = "step: ";
} //_CODE_:textfield1:357951:

public void button1_click3(GButton source, GEvent event) { //_CODE_:button1:624903:
  println("MOTOR ON");
  myPort.write("MN");
} //_CODE_:button1:624903:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:946019:
  println("MOTOR OFF");
  myPort.write("MF");
} //_CODE_:button2:946019:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button_set:805177:
  println("button_set - GButton >> GEvent." + event + " @ " + millis());
  String toSend;
  toSend = textfield1.getText();
  myPort.write("a" + toSend);
} //_CODE_:button_set:805177:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  button_fanOn = new GButton(this, 308, 115, 80, 30);
  button_fanOn.setText("FANS ON");
  button_fanOn.addEventHandler(this, "button1_click1");
  button_fansOff = new GButton(this, 308, 152, 80, 30);
  button_fansOff.setText("FANS OFF");
  button_fansOff.addEventHandler(this, "button1_click2");
  checkbox1 = new GCheckbox(this, 100, 160, 120, 20);
  checkbox1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox1.setText("Clockwise");
  checkbox1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  checkbox1.setOpaque(false);
  checkbox1.addEventHandler(this, "checkbox1_clicked1");
  textfield1 = new GTextField(this, 98, 200, 60, 20, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 10, 160, 80, 20);
  label1.setText("Direction");
  label1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label1.setOpaque(false);
  label2 = new GLabel(this, 10, 199, 80, 20);
  label2.setText("Step");
  label2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label2.setOpaque(false);
  label3 = new GLabel(this, 8, 112, 211, 21);
  label3.setText("MOTOR");
  label3.setTextBold();
  label3.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label3.setOpaque(false);
  button1 = new GButton(this, 10, 250, 80, 30);
  button1.setText("MOTOR ON");
  button1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button1.addEventHandler(this, "button1_click3");
  button2 = new GButton(this, 100, 250, 80, 30);
  button2.setText("MOTOR OFF");
  button2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  button_set = new GButton(this, 170, 193, 80, 30);
  button_set.setText("SET STEP");
  button_set.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button_set.addEventHandler(this, "button3_click1");
  label4 = new GLabel(this, 8, 74, 382, 36);
  label4.setText("Telescope Control Panel");
  label4.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label4.setOpaque(false);
  label5 = new GLabel(this, 395, 272, 80, 20);
  label5.setText("My label");
  label5.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button_fanOn; 
GButton button_fansOff; 
GCheckbox checkbox1; 
GTextField textfield1; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GButton button1; 
GButton button2; 
GButton button_set; 
GLabel label4; 
GLabel label5; 

